export AZUREML_NATIVE_SHARE_DIRECTORY="/home/laks/mnt/azureml-share"
export TELEMETRY_STORAGE_ACCOUNT_NAME=$2
export TELEMETRY_STORAGE_ACCOUNT_KEY=$3
export STAGING_STORAGE_ACCOUNT_NAME=$2
export STAGING_STORAGE_ACCOUNT_KEY=$3
export TELEMETRY_CONTAINER_NAME="telemetry"